name: Build signed release APK

on:
  push:
    branches: ['**']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAIN_PROJECT_MODULE: app
  APK_FILE_NAME: UmihiMusic
  STORE_FILE: ${{ github.workspace }}/app/release-key.jks
  APK_OUTPUT: /build/outputs/apk/release/app-release.apk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set Up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Decode keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ${{ env.STORE_FILE }}

      - name: Build release APK
        run: ./gradlew assembleRelease -Pbeta=false -PgitHash=${{ github.sha }}
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_FILE: ${{ env.STORE_FILE }}

      - name: Rename APK
        run: mv ${{ env.MAIN_PROJECT_MODULE }}${{ env.APK_OUTPUT }} ${{ env.APK_FILE_NAME }}.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v7
        with:
          name: UmihiMusic
          path: ${{ env.APK_FILE_NAME }}.apk
          overwrite: true

      - name: Delete keystore
        if: always()
        run: rm -f ${{ env.STORE_FILE }}
